HighlightColour = "Lime"
ContextColour = "LightGray"
MultiSelectLimit = 1000
NumContextLines = 0
UpdateIntervalLocalDrive = 500
SFTP_URLs = []
HeaderFormat = "[{0}-{1}:{2}] {3} {4} [{5}] - "
HeaderFormatKeys = ["pid", "tid", "seq", "time_format=yyyy-MM-dd", "time_formats=|HH:mm:ss.fff|HH:mm:ss", "level", "PARSER_END"]
Modules = ["Radar"]
Filter1 = ["\"ps_", "\"cmd_", "\"process_create\""]
Filter2 = ["FILTER", "MERGE", "RULESCTL"]
Filter3 = []
